Repository commercionetwork/commercionetwork, pull requests merged in 2019-10, with the labels that each got.

#40 Pairwise Did power up system implementation
  app/app.go
  docs/x/id/README.md
  docs/x/id/creating-pairwise-did.md
  docs/x/id/tx/did-power-up.md
  docs/x/id/tx/invalidate-did-deposit-request.md
  docs/x/id/tx/invalidate-did-power-up-request.md
  docs/x/id/tx/move-deposit.md
  docs/x/id/tx/request-did-deposit.md
  docs/x/id/tx/request-did-power-up.md
  x/common/types/strings.go
  x/id/alias.go
  x/id/client/cli/query.go
  x/id/client/rest/query.go
  x/id/genesis.go
  x/id/handler.go
  x/id/handler_test.go
  x/id/internal/keeper/keeper.go
  x/id/internal/keeper/keeper_test.go
  x/id/internal/keeper/querier.go
  x/id/internal/keeper/querier_test.go
  x/id/internal/keeper/test_commons.go
  x/id/internal/types/codec.go
  x/id/internal/types/did_deposit_request.go
  x/id/internal/types/did_deposit_request_test.go
  x/id/internal/types/did_power_up_request.go
  x/id/internal/types/did_power_up_request_test.go
  x/id/internal/types/keys.go
  x/id/internal/types/msgs.go
  x/id/internal/types/msgs_test.go
  x/id/internal/types/request_status.go
  x/id/module.go
Labels: R4R

#42 CommercioMINT implementation
  CHANGELOG.md
  Makefile
  app/app.go
  cmd/cnd/main.go
  docs/.vuepress/config.js
  docs/README.md
  docs/x/mint/README.md
  docs/x/mint/query/read-cdp.md
  docs/x/mint/query/read-cdps.md
  docs/x/mint/tx/close-cdp.md
  docs/x/mint/tx/open-cdp.md
  go.mod
  go.sum
  x/accreditations/internal/keeper/querier_test.go
  x/accreditations/module.go
  x/docs/handler.go
  x/docs/internal/keeper/keeper.go
  x/docs/internal/keeper/querier.go
  x/docs/internal/types/document_metadata_test.go
  x/docs/module.go
  x/genutil/client/cli/genaccounts.go
  x/genutil/client/cli/migrate.go
  x/genutil/legacy/v120/migrate.go
  x/government/module.go
  x/id/handler_test.go
  x/id/module.go
  x/memberships/module.go
  x/mint/alias.go
  x/mint/client/cli/query.go
  x/mint/client/cli/tx.go
  x/mint/client/rest/query.go
  x/mint/genesis.go
  x/mint/handler.go
  x/mint/handler_test.go
  x/mint/internal/keeper/keeper.go
  x/mint/internal/keeper/keeper_test.go
  x/mint/internal/keeper/querier.go
  x/mint/internal/keeper/querier_test.go
  x/mint/internal/keeper/test_commons.go
  x/mint/internal/types/cdp.go
  x/mint/internal/types/cdpRequest.go
  x/mint/internal/types/cdpRequest_test.go
  x/mint/internal/types/cdp_test.go
  x/mint/internal/types/codec.go
  x/mint/internal/types/keys.go
  x/mint/internal/types/msgs.go
  x/mint/internal/types/msgs_test.go
  x/mint/module.go
  x/pricefeed/abci.go
  x/pricefeed/alias.go
  x/pricefeed/internal/keeper/keeper.go
  x/pricefeed/internal/keeper/keeper_test.go
  x/pricefeed/internal/types/price.go
  x/pricefeed/module.go
  x/tbr/internal/keeper/test_commons.go
  x/tbr/module.go
Labels: R4R

#46 Specific accounts token sending blocking
  app/app.go
  docs/.vuepress/config.js
  docs/developers/listing-transactions.md
  docs/x/bank/README.md
  docs/x/bank/blocked-accounts.md
  docs/x/bank/tx/account-blocking.md
  docs/x/bank/tx/account-unlock.md
  docs/x/bank/tx/send.md
  x/common/types/addresses.go
  x/encapsulated/bank/alias.go
  x/encapsulated/bank/client/rest/rest.go
  x/encapsulated/bank/genesis.go
  x/encapsulated/bank/handler.go
  x/encapsulated/bank/internal/keeper/keeper.go
  x/encapsulated/bank/internal/keeper/keeper_test.go
  x/encapsulated/bank/internal/keeper/querier.go
  x/encapsulated/bank/internal/keeper/test_commons.go
  x/encapsulated/bank/internal/types/codec.go
  x/encapsulated/bank/internal/types/keys.go
  x/encapsulated/bank/internal/types/msgs.go
  x/encapsulated/bank/module.go
  x/encapsulated/crisis/module.go
  x/encapsulated/gov/module.go
  x/encapsulated/mint/module.go
  x/encapsulated/staking/module.go
  x/pricefeed/genesis.go
Labels: R4M

#59 Pairwise DID msgs update
  x/id/internal/keeper/handler.go
  x/id/internal/keeper/handler_test.go
  x/id/internal/types/did_deposit_request.go
  x/id/internal/types/did_deposit_request_test.go
  x/id/internal/types/did_power_up_request.go
  x/id/internal/types/did_power_up_request_test.go
  x/id/internal/types/msgs.go
  x/id/internal/types/msgs_test.go
Labels: R4R

#57 Do not keep a local Version variable
  Makefile
  app/app.go
  cmd/cncli/main.go
  cmd/cnd/main.go
  go.mod
Labels: R4R, enhancement

#64 Solve nil pointer dereference in id keeper
  x/id/internal/keeper/keeper.go
Labels: R4R, enhancement, help wanted
