Repository commercionetwork/commercionetwork, pull requests merged in 2019-11, with the labels that each got.

#63 UUID validation with go.uuid
  go.mod
  go.sum
  x/docs/internal/types/document.go
  x/docs/internal/types/document_test.go
Labels: R4R, enhancement

#66 Do not validate content_uri
  x/docs/internal/types/document.go
Labels: R4M, bug, enhancement

#67 Fix btcd retag issue
  go.mod
  go.sum
Labels: R4R, enhancement, help wanted

#71 Added tests for the common types
  x/common/types/addresses.go
  x/common/types/addresses_test.go
  x/common/types/dec_coins_test.go
  x/common/types/strings.go
  x/common/types/strings_test.go
Labels: R4R

#69 Document work
  docs/x/docs/tx/send-document.md
  x/docs/internal/types/document.go
  x/docs/internal/types/document_checksum.go
  x/docs/internal/types/document_checksum_test.go
  x/docs/internal/types/document_encryption_data.go
  x/docs/internal/types/document_encryption_data_test.go
  x/docs/internal/types/document_encryption_key_test.go
  x/docs/internal/types/document_metadata_test.go
  x/docs/internal/types/document_receipt.go
  x/docs/internal/types/document_receipt_id.go
  x/docs/internal/types/document_receipt_id_test.go
  x/docs/internal/types/document_receipt_test.go
  x/docs/internal/types/document_test.go
  x/docs/internal/types/metadata_test.go
  x/docs/internal/types/msgs_test.go
Labels: R4R, enhancement, help wanted, wip

#72 Id module tests
  x/id/internal/types/common.go
  x/id/internal/types/common_test.go
  x/id/internal/types/did_deposit_request.go
  x/id/internal/types/msgs.go
  x/id/internal/types/msgs_test.go
  x/id/internal/types/proof.go
  x/id/internal/types/proof_test.go
  x/id/internal/types/pub_key.go
  x/id/internal/types/pub_key_test.go
  x/id/internal/types/request_status.go
  x/id/internal/types/request_status_test.go
  x/id/internal/types/service.go
  x/id/internal/types/service_test.go
Labels: R4R, enhancement

#73 Memberships test
  docs/x/id/query/read-identity.md
  x/docs/internal/keeper/keeper.go
  x/memberships/internal/keeper/alias_function.go
  x/memberships/internal/keeper/commons_test.go
  x/memberships/internal/keeper/handler.go
  x/memberships/internal/keeper/handler_test.go
  x/memberships/internal/keeper/keeper.go
  x/memberships/internal/keeper/keeper_credentials.go
  x/memberships/internal/keeper/keeper_credentials_test.go
  x/memberships/internal/keeper/keeper_invite_test.go
  x/memberships/internal/keeper/keeper_invites.go
  x/memberships/internal/keeper/keeper_invites_test.go
  x/memberships/internal/keeper/keeper_rewards.go
  x/memberships/internal/keeper/keeper_rewards_test.go
  x/memberships/internal/keeper/keeper_test.go
  x/memberships/internal/keeper/keeper_tsp.go
  x/memberships/internal/keeper/keeper_tsp_test.go
  x/memberships/internal/keeper/querier.go
  x/memberships/internal/keeper/querier_test.go
  x/memberships/internal/types/credential.go
  x/memberships/internal/types/credential_test.go
  x/memberships/internal/types/invite.go
  x/memberships/internal/types/invite_test.go
  x/memberships/internal/types/membership.go
  x/memberships/internal/types/membership_test.go
  x/memberships/internal/types/msgs.go
  x/memberships/internal/types/msgs_test.go
  x/pricefeed/internal/keeper/keeper.go
Labels: R4R, enhancement
