Repository commercionetwork/commercionetwork, pull requests merged in 2019-09, with the labels that each got.

#25 Singleton removal from tests
  go.mod
  x/docs/alias.go
  x/docs/handler_test.go
  x/docs/internal/keeper/keeper_test.go
  x/docs/internal/keeper/querier_test.go
  x/docs/internal/keeper/test_commons.go
  x/government/internal/keeper/keeper_test.go
  x/government/internal/keeper/querier.go
  x/government/internal/keeper/querier_test.go
  x/government/internal/keeper/test_commons.go
  x/id/alias.go
  x/id/handler_test.go
  x/id/internal/keeper/keeper_test.go
  x/id/internal/keeper/querier_test.go
  x/id/internal/keeper/test_commons.go
  x/memberships/alias.go
  x/memberships/handler_test.go
  x/memberships/internal/keeper/keeper_test.go
  x/memberships/internal/keeper/querier_test.go
  x/memberships/internal/keeper/test_commons.go
Labels: in review

#23 Transactions Block Reward implementation
  go.sum
  x/tbr/abci.go
  x/tbr/alias.go
  x/tbr/client/cli/query.go
  x/tbr/client/cli/tx.go
  x/tbr/genesis.go
  x/tbr/handler.go
  x/tbr/handler_test.go
  x/tbr/internal/keeper/keeper.go
  x/tbr/internal/keeper/keeper_test.go
  x/tbr/internal/keeper/querier.go
  x/tbr/internal/keeper/querier_test.go
  x/tbr/internal/keeper/test_commons.go
  x/tbr/internal/types/codec.go
  x/tbr/internal/types/keys.go
  x/tbr/internal/types/msgs.go
  x/tbr/internal/types/msgs_test.go
  x/tbr/module.go
Labels: in review

#24 User accreditation implementation
  app/app.go
  cmd/cnd/main.go
  x/accreditations/alias.go
  x/accreditations/client/cli/query.go
  x/accreditations/client/cli/tx.go
  x/accreditations/genesis.go
  x/accreditations/handler.go
  x/accreditations/handler_test.go
  x/accreditations/internal/keeper/keeper.go
  x/accreditations/internal/keeper/keeper_test.go
  x/accreditations/internal/keeper/querier.go
  x/accreditations/internal/keeper/querier_test.go
  x/accreditations/internal/keeper/test_commons.go
  x/accreditations/internal/types/accreditations.go
  x/accreditations/internal/types/codec.go
  x/accreditations/internal/types/keys.go
  x/accreditations/internal/types/msgs.go
  x/accreditations/internal/types/msgs_test.go
  x/accreditations/module.go
  x/gencommands/client/cli/add_genesis_accreditation_signer.go
Labels: in review

#27 CommercioDOCS improvements
  cmd/cncli/main.go
  docs/x/docs/tx/share-document.md
  x/accreditations/handler_test.go
  x/accreditations/internal/keeper/keeper.go
  x/accreditations/internal/keeper/keeper_test.go
  x/accreditations/internal/keeper/querier_test.go
  x/accreditations/module.go
  x/common/types/addresses.go
  x/docs/alias.go
  x/docs/client/cli/tx.go
  x/docs/genesis.go
  x/docs/handler.go
  x/docs/handler_test.go
  x/docs/internal/keeper/keeper.go
  x/docs/internal/keeper/keeper_test.go
  x/docs/internal/keeper/querier.go
  x/docs/internal/keeper/querier_test.go
  x/docs/internal/keeper/test_commons.go
  x/docs/internal/types/document.go
  x/docs/internal/types/document_checksum.go
  x/docs/internal/types/document_checksum_test.go
  x/docs/internal/types/document_encryption_data.go
  x/docs/internal/types/document_encryption_data_test.go
  x/docs/internal/types/document_encryption_key.go
  x/docs/internal/types/document_encryption_key_test.go
  x/docs/internal/types/document_id.go
  x/docs/internal/types/document_metadata.go
  x/docs/internal/types/document_metadata_test.go
  x/docs/internal/types/document_test.go
  x/docs/internal/types/keys.go
  x/docs/internal/types/metadata.go
  x/docs/internal/types/msgs.go
  x/docs/internal/types/msgs_test.go
  x/id/internal/keeper/keeper_test.go
  x/id/internal/types/msgs.go
  x/memberships/internal/types/membership.go
  x/memberships/internal/types/msgs.go
Labels: ready to merge

#34 CommercioTBR fixes
  app/app.go
  cmd/cnd/main.go
  docs/.vuepress/config.js
  docs/chain-start/README.md
  docs/x/docs/tx/new.md
  docs/x/docs/tx/send-document.md
  docs/x/tbr/README.md
  package-lock.json
  package.json
  x/accreditations/genesis.go
  x/gencommands/client/cli/set_genesis_tbr_pool.go
  x/tbr/abci.go
  x/tbr/alias.go
  x/tbr/genesis.go
  x/tbr/internal/keeper/keeper.go
  x/tbr/internal/keeper/keeper_test.go
  x/tbr/internal/keeper/test_commons.go
  x/tbr/internal/types/keys.go
  x/tbr/module.go
Labels: R4R
