Repository commercionetwork/commercionetwork, pull requests merged in 2020-04, with the labels that each got.

#110 x/commerciomint: internal state's new implementation
  app/app.go
  go.mod
  x/commerciomint/client/cli/query.go
  x/commerciomint/client/cli/tx.go
  x/commerciomint/genesis.go
  x/commerciomint/genesis_test.go
  x/commerciomint/keeper/handler.go
  x/commerciomint/keeper/handler_test.go
  x/commerciomint/keeper/invariants.go
  x/commerciomint/keeper/invariants_test.go
  x/commerciomint/keeper/keeper.go
  x/commerciomint/keeper/keeper_test.go
  x/commerciomint/keeper/querier.go
  x/commerciomint/keeper/querier_test.go
  x/commerciomint/keeper/test_commons.go
  x/commerciomint/module.go
  x/commerciomint/module_test.go
  x/commerciomint/types/cdp.go
  x/commerciomint/types/cdp_test.go
  x/commerciomint/types/msgs.go
  x/commerciomint/types/msgs_test.go
  x/commerciomint/types/position.go
  x/commerciomint/types/position_test.go
Labels: R4R

#116 Fixed DDO creation CLI command
  x/id/client/cli/tx.go
Labels: bug, enhancement

#122 Query membership for user via REST
  x/memberships/client/rest/query.go
Labels: R4R, enhancement

#121 Remove add-genesis-membership, assign black membership to government
  cmd/cnd/main.go
  x/gencommands/client/cli/add_genesis_membership.go
  x/gencommands/client/cli/set_genesis_government_address.go
Labels: R4R, enhancement
